#ifndef TASK_CONFIG_H
#define TASK_CONFIG_H

// Defaults
#define DEFAULT_TASK_STACK_SIZE 2048
#define DEFAULT_QUEUE_LENGTH 8
#define DEFAULT_TASK_PRIORITY 10 // Low priority numbers denote low priority tasks.

// Task Snacky
#define TASK_SNACKY_TASK_NAME "TASK_SNACKY"
#define TASK_SNACKY_STACK_SIZE (DEFAULT_TASK_STACK_SIZE)
#define TASK_SNACKY_QUEUE_LENGTH (DEFAULT_QUEUE_LENGTH)
#define TASK_SNACKY_TASK_PRIORITY (DEFAULT_TASK_PRIORITY)


// Task Reader
#define TASK_READER_TASK_NAME "TASK_READER"
#define TASK_READER_STACK_SIZE (DEFAULT_TASK_STACK_SIZE)
#define TASK_READER_QUEUE_LENGTH (DEFAULT_QUEUE_LENGTH)
#define TASK_READER_TASK_PRIORITY (DEFAULT_TASK_PRIORITY - 1)



#endif