#ifndef TASK_CONFIG_H
#define TASK_CONFIG_H

// Defaults
#define DEFAULT_TASK_STACK_SIZE 2048
#define DEFAULT_QUEUE_LENGTH 8

#define TASK_SNACKY_STACK_SIZE (DEFAULT_TASK_STACK_SIZE)
#define TASK_READER_STACK_SIZE (DEFAULT_TASK_STACK_SIZE)



#endif